name: game_boy_graphics_editor
description: Edit GBDK graphics source files

version: 2.1.1+7

publish_to: 'none'

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  file_picker: ^10.3.6
  image: ^4.1.0
  flutter_bloc: ^9.1.0
  replay_bloc: ^0.3.0
  two_dimensional_scrollables: ^0.3.0
  shared_preferences: ^2.2.0
  path: ^1.8.3
  http: ^1.6.0
  equatable: ^2.0.7
  petitparser: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

